config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles

  get 'articles', to: 'articles#index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord 
  validates :title, presence: true, length: {minimum: 6, maximum:100}
  validates :description, presence: true, length: {minimum: 10, maximum:300}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  #allow_browser versions: :modern

  def hello
    render html: "hello World"

  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]


  def show

  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end





  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render 'new'
    end
  end


  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path

  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>

  <h2>The following errors prevented the article from being saved:</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with(model: @article, local: true) do |f| %>
<div class="shadow rounded outline">
  <br>
  
  <div class="form-group row">
    <%= f.label :title, class:"col-2 col-form-label my-title" %>
    <div class="col-7">
      <%= f.text_field :title, class:"form-control shadow mb-5 bg-white rounded" %>
    </div>
  </div>
  <br>

  <div class="form-group row">
    <%= f.label :description, class:"col-2 col-form-label my-title" %>
    <div class="col-7">
      <%= f.text_area :description,rows:10, class:"form-control shadow mb-5 bg-white rounded" %>
    </div>
  </div>
  <br>
  <div>
    <%= f.submit class:"btn btn-primary btn-lg my-button"%>
  </div>
  <br>

</div>
<% end %>
<br>
<%= button_to 'return to all articles',articles_path, method: :get, class:"btn btn-primary btn-lg"%>

app/views/articles/edit.html.erb
<h1>Edit an article</h1>

<%= render 'form'%>


app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles listing page</h1>


<% @articles.each do |article| %>
    <div class="card text-center my-card shadow mb-5 bg-white rounded">
        <div class="card-header">
            Muhammad Abdullah
        </div>
        <div class="card-body">
            <h5 class="card-title for-hover"><%= link_to article.title, article_path(article), class:"card-title for-hover"%></h5>
            <p class="card-text"><%=article.description%></p>
            <%= button_to 'Show', article_path(article), class:"btn btn-outline-primary my-button", method: :get %> <%= button_to 'Edit', edit_article_path(article),class:"btn btn-outline-primary my-button", method: :get %> <%= button_to 'Delete', article_path(article),class:"btn btn-outline-primary my-button", method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
        <div class="card-footer text-body-secondary">
            <small>Created : <%= time_ago_in_words(article.created_at)%> ago, </small>
            <small>Updated : <%= time_ago_in_words(article.updated_at)%> ago</small>

        </div>
    </div>


<%end%>

<br>
<br>

<p><%= button_to 'New Article', new_article_path, method: :get, class:"btn btn-primary btn-lg my-button"%></p>
<p><%= button_to 'Go to Home Page ', root_path, method: :get, class:"btn btn-primary btn-lg my-button"%></p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>


<%= render 'form'%>



app/views/articles/show.html.erb
<h1>showing article details</h1>



<div class="card text-center my-card shadow mb-5 bg-white rounded">
<div class="card-header">
    Muhammad Abdullah
</div>
<div class="card-body">
    <h5 class="card-title for-hover"><%= link_to @article.title, article_path(@article), class:"card-title for-hover"%></h5>
    <p class="card-text my-text"><%= simple_format(@article.description) %></p>
    <%= button_to 'Edit', edit_article_path(@article),class:"btn btn-outline-primary my-button", method: :get %> 
    <%= button_to 'Delete', article_path(@article),class:"btn btn-outline-primary my-button", method: :delete, data: {confirm: "Are you sure?"} %>
</div>
<div class="card-footer text-body-secondary">
    <small>Created : <%= time_ago_in_words(@article.created_at)%> ago, </small>
    <small>Updated : <%= time_ago_in_words(@article.updated_at)%> ago</small>

</div>
</div>

<p><%= button_to 'Return to artcle listing', articles_path(@article), method: :get,class:"btn btn-primary btn-lg my-button" %></p>

app/views/layouts/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active position-relative">
      <%= image_tag "blog1.jpg", class: "d-block w-100", alt: "Slide 1" %>
      <button class="carousel-button btn btn-primary">Click Here</button>
    </div>
    <div class="carousel-item position-relative">
      <%= image_tag "blog2.jpg", class: "d-block w-100", alt: "Slide 2" %>
      <button class="carousel-button btn btn-primary">Click Here</button>
    </div>
    <div class="carousel-item position-relative">
      <%= image_tag "blog3.jpg", class: "d-block w-100", alt: "Slide 3" %>
      <button class="carousel-button btn btn-primary">Click Here</button>
    </div>
  </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon"></span>
  </button>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-light text-center text-lg-start mt-5">
  <div class="container p-4">
    <p class="text-center mb-0">
      © <%= Time.now.year %> AlphaBlog. All rights reserved.
    </p>

    <p class="text-center mb-0">
      <%= link_to "Muhammad Abdullah", "https://www.linkedin.com/in/iammuhammadabdullah/", id:"linkedin"%>
    </p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
    <%flash.each do |name, msg|%>
      <%=msg%>
    <%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHA BLOG", root_path, class:"navbar-brand", id:"logo" %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Artilces", articles_path, class:"nav-link"%>

      </li>
            <li class="nav-item">
        <%= link_to "About", about_path, class:"nav-link"%>

      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
          data-bs-toggle="dropdown" aria-expanded="false">
          Articles 
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><%= link_to "About", about_path, class:"dropdown-item"%></li>
          <li><%= link_to "All Articles", articles_path, class:"dropdown-item"%></li>
          <li><%= link_to "New Article", new_article_path, class:"dropdown-item"%></li>

          <li><%= link_to "Home", root_path, class:"dropdown-item"%></li>
        </ul>
      </li>

    </ul>

    <form class="d-flex" role="search">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hello" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
  crossorigin="anonymous">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="page">

    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
  crossorigin="anonymous"></script>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="page">
<h1>This is the about page</h1>


<p><%= button_to 'Go to Home Page ', root_path, method: :get, class:"btn btn-primary btn-lg my-button"%></p>

<p><%= button_to 'Go to All Articles', articles_path, method: :get, class:"btn btn-primary btn-lg my-button"%></p>
</div>

app/views/pages/home.html.erb
<div class="page">

<h1>This is the root page</h1>
<%= render 'layouts/carousel' %>

<p><%= button_to 'Go to All Articles', articles_path, method: :get, class:"btn btn-primary btn-lg my-button"%></p>
<p><%= button_to 'Go to About Page ', about_path, method: :get, class:"btn btn-primary btn-lg my-button"%></p>
</div>